/**
 * Reads the folder-scanned content manifest and shapes it for the UI.
 * The manifest is regenerated by `scripts/generate-content.mjs`.
 */
import raw from '@/generated/content.json'
import { categoryCopy } from '@/data/site'

export type MediaType = 'image' | 'video' | 'embed'

export type WorkItem = {
  id: string
  title: string
  description: string
  tags: string[]
  type: MediaType
  src: string
  poster: string
  embed?: string
  width: number
  height: number
  bytes?: number
}

export type WorkSection = {
  slug: string
  title: string
  description: string
  order: number
  breadcrumb: string[]
  count: number
  items: WorkItem[]
}

export type WorkCategory = {
  slug: string
  title: string
  dirName: string
  tagline: string
  description: string
  order: number
  accent: string
  count: number
  cover: string
  coverType: MediaType
  sections: WorkSection[]
}

type Manifest = {
  generatedAt: string
  totals: { categories: number; sections: number; items: number }
  categories: WorkCategory[]
}

const manifest = raw as unknown as Manifest

/** Prefix a public/ path with Vite's base so sub-folder deploys keep working. */
export function asset(path: string): string {
  if (!path) return ''
  if (/^(https?:)?\/\//.test(path) || path.startsWith('data:')) return path
  const base = import.meta.env.BASE_URL || '/'
  return `${base.replace(/\/$/, '')}/${path.replace(/^\.?\//, '')}`
}

function hydrate(category: WorkCategory): WorkCategory {
  const copy = categoryCopy[category.slug]
  return {
    ...category,
    tagline: category.tagline || copy?.tagline || 'Selected work',
    description: category.description || copy?.description || '',
    cover: asset(category.cover),
    sections: category.sections.map((section) => ({
      ...section,
      items: section.items.map((item) => ({
        ...item,
        src: item.type === 'embed' ? item.src : asset(item.src),
        poster: asset(item.poster),
      })),
    })),
  }
}

export const categories: WorkCategory[] = manifest.categories.map(hydrate)
export const totals = manifest.totals

export function getCategory(slug?: string): WorkCategory | undefined {
  if (!slug) return undefined
  return categories.find((c) => c.slug === slug)
}

/** Everything, flattened — used by the hero collage and the "next up" rail. */
export const allItems: Array<WorkItem & { category: string; categorySlug: string; section: string }> =
  categories.flatMap((c) =>
    c.sections.flatMap((s) =>
      s.items.map((item) => ({ ...item, category: c.title, categorySlug: c.slug, section: s.title })),
    ),
  )

export function nextCategory(slug: string): WorkCategory | undefined {
  if (categories.length < 2) return undefined
  const index = categories.findIndex((c) => c.slug === slug)
  if (index === -1) return categories[0]
  return categories[(index + 1) % categories.length]
}

export const hasContent = categories.length > 0
